DELETE http://localhost:3003/api/blogs/6011b029e3a14eb89081c312
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVTRVIgMSIsImlkIjoiNjAwZWRmNzFiMzFhMWExODY4ZDQ2MmUxIiwiaWF0IjoxNjExNjAxMTY3fQ.ywueHedHD8uZNBbfNVsttfAXyuUdHJuxMlrGFLromAM